services:
  mysql-auth:
    image: mysql:8
    container_name: mysql-auth
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-empleado:
    image: mysql:8
    container_name: mysql-empleado
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_empleado
    ports:
      - "3309:3306"
    volumes:
      - mysql_empleado_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-categoria:
    image: mysql:8
    container_name: mysql-categoria
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_categoria
    ports:
      - "3308:3306"
    volumes:
      - mysql_categoria_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-cliente:
    image: mysql:8
    container_name: mysql-cliente
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_cliente
    ports:
      - "3311:3306"
    volumes:
      - mysql_cliente_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-producto:
    image: mysql:8
    container_name: mysql-producto
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_producto
    ports:
      - "3312:3306"
    volumes:
      - mysql_producto_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-inventario:
    image: mysql:8
    container_name: mysql-inventario
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_inventario
    ports:
      - "3313:3306"
    volumes:
      - mysql_inventario_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-carrito:
    image: mysql:8
    container_name: mysql-carrito
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_carrito
    ports:
      - "3310:3306"
    volumes:
      - mysql_carrito_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-pedido:
    image: mysql:8
    container_name: mysql-pedido
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_pedido
    ports:
      - "3314:3306"
    volumes:
      - mysql_pedido_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-pago:
    image: mysql:8
    container_name: mysql-pago
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_pago
    ports:
      - "3315:3306"
    volumes:
      - mysql_pago_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-devolucion:
    image: mysql:8
    container_name: mysql-devolucion
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms_devolucion
    ports:
      - "3316:3306"
    volumes:
      - mysql_devolucion_data:/var/lib/mysql
    networks:
      - backend-network

  ms-eureka:
    build: ./ms-eureka
    container_name: ms-eureka
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - backend-network

  ms-auth:
    build: ./ms-auth
    container_name: ms-auth
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql-auth:3306/ms_auth
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-auth
      - ms-eureka
    networks:
      - backend-network

  ms-empleado:
    build: ./ms-empleado
    container_name: ms-empleado
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:mysql://mysql-empleado:3306/ms_empleado
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-empleado
      - ms-eureka
      - ms-auth
    networks:
      - backend-network

  ms-categoria:
    build: ./ms-categoria
    container_name: ms-categoria
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:mysql://mysql-categoria:3306/ms_categoria
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-categoria
      - ms-eureka
      - ms-auth
    networks:
      - backend-network

  ms-cliente:
    build: ./ms-cliente
    container_name: ms-cliente
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      DB_URL: jdbc:mysql://mysql-cliente:3306/ms_cliente
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
    depends_on:
      - mysql-cliente
      - ms-auth
    networks:
      - backend-network

  ms-producto:
    build: ./ms-producto
    container_name: ms-producto
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      DB_URL: jdbc:mysql://mysql-producto:3306/ms_producto
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
      CATEGORIA_SERVICE_URL: http://ms-categoria:8082/api/v1/categorias/
    depends_on:
      - mysql-producto
      - ms-auth
      - ms-categoria
    networks:
      - backend-network

  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      DB_URL: jdbc:mysql://mysql-inventario:3306/ms_inventario
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
    depends_on:
      - mysql-inventario
      - ms-auth
      - ms-producto
    networks:
      - backend-network

  ms-carrito:
    build: ./ms-carrito
    container_name: ms-carrito
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DB_URL: jdbc:mysql://mysql-carrito:3306/ms_carrito
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
      EUREKA_URL: http://ms-eureka:8761/eureka/
      CLIENTE_SERVICE_URL: http://ms-cliente:8083/api/v1/clientes/
      PRODUCTO_SERVICE_URL: http://ms-producto:8084/api/v1/productos/
    depends_on:
      - mysql-carrito
      - ms-eureka
      - ms-auth
      - ms-cliente
      - ms-producto
    networks:
      - backend-network

  ms-pedido:
    build: ./ms-pedido
    container_name: ms-pedido
    restart: unless-stopped
    ports:
      - "8087:8087"
    environment:
      DB_URL: jdbc:mysql://mysql-pedido:3306/ms_pedido
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
      CLIENTE_SERVICE_URL: http://ms-cliente:8083/api/v1/clientes/
      PRODUCTO_SERVICE_URL: http://ms-producto:8084/api/v1/productos/
    depends_on:
      - mysql-pedido
      - ms-auth
      - ms-cliente
      - ms-producto
    networks:
      - backend-network

  ms-pago:
    build: ./ms-pago
    container_name: ms-pago
    restart: unless-stopped
    ports:
      - "8092:8090"
    environment:
      DB_URL: jdbc:mysql://mysql-pago:3306/ms_pago
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
    depends_on:
      - mysql-pago
      - ms-auth
      - ms-pedido
    networks:
      - backend-network

  ms-devolucion:
    build: ./ms-devolucion
    container_name: ms-devolucion
    restart: unless-stopped
    ports:
      - "8091:8091"
    environment:
      DB_URL: jdbc:mysql://mysql-devolucion:3306/ms_devolucion
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: producto_super_secreto_especial123456789
    depends_on:
      - mysql-devolucion
      - ms-auth
      - ms-pedido
      - ms-pago
    networks:
      - backend-network

  ms-gateway:
    build: ./ms-gateway
    container_name: ms-gateway
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - ms-eureka
      - ms-auth
      - ms-empleado
      - ms-categoria
      - ms-cliente
      - ms-producto
      - ms-inventario
      - ms-carrito
      - ms-pedido
      - ms-pago
      - ms-devolucion
    networks:
      - backend-network

networks:
  backend-network:

volumes:
  mysql_auth_data:
  mysql_empleado_data:
  mysql_categoria_data:
  mysql_cliente_data:
  mysql_producto_data:
  mysql_inventario_data:
  mysql_carrito_data:
  mysql_pedido_data:
  mysql_pago_data:
  mysql_devolucion_data:

