spring.application.name=ms-gateway
spring.cloud.gateway.server.webmvc.routes[0].id=ms-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-auth
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webmvc.routes[1].id=ms-empleado
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-empleado
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/empleados/**
spring.cloud.gateway.server.webmvc.routes[2].id=ms-categoria
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-categoria
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/v1/categorias/**
spring.cloud.gateway.server.webmvc.routes[3].id=ms-cliente
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://ms-cliente
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/v1/clientes/**
spring.cloud.gateway.server.webmvc.routes[4].id=ms-producto
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ms-producto
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/v1/productos/**
spring.cloud.gateway.server.webmvc.routes[5].id=ms-inventario
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://ms-inventario
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/v1/inventarios/**
spring.cloud.gateway.server.webmvc.routes[6].id=ms-carrito
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://ms-carrito
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/v1/carritos/**
spring.cloud.gateway.server.webmvc.routes[7].id=ms-pedido
spring.cloud.gateway.server.webmvc.routes[7].uri=lb://ms-pedido
spring.cloud.gateway.server.webmvc.routes[7].predicates[0]=Path=/api/v1/pedidos/**
spring.cloud.gateway.server.webmvc.routes[8].id=ms-pago
spring.cloud.gateway.server.webmvc.routes[8].uri=lb://ms-pago
spring.cloud.gateway.server.webmvc.routes[8].predicates[0]=Path=/api/v1/pagos/**
spring.cloud.gateway.server.webmvc.routes[9].id=ms-devolucion
spring.cloud.gateway.server.webmvc.routes[9].uri=lb://ms-devolucion
spring.cloud.gateway.server.webmvc.routes[9].predicates[0]=Path=/api/v1/devoluciones/**
server.port=${SERVER_PORT:8090}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
management.endpoints.web.exposure.include=health,info