spring.application.name=ms-pedido
server.port=${SERVER_PORT:8087}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ms_pedido}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET:producto_super_secreto_especial123456789}
cliente.service.url=${CLIENTE_SERVICE_URL:http://localhost:8083/api/clientes/}
producto.service.url=${PRODUCTO_SERVICE_URL:http://localhost:8084/api/productos/}
