spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-auth
              uri: lb://ms-auth
              predicates:
                - Path=/auth/**
            - id: ms-categoria
              uri: lb://ms-categoria
              predicates:
                - Path=/api/categorias/**
            - id: ms-empleado
              uri: lb://ms-empleado
              predicates:
                - Path=/api/empleados/**
            - id: ms-carrito
              uri: lb://ms-carrito
              predicates:
                - Path=/api/carritos/**

server:
  port: ${SERVER_PORT:8090}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
